springdoc:
  swagger-ui: # for swagger ui
    path: /swagger-ui.html
  api-docs: # for Open API yaml
    path: /v3/api-docs
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  cloud:
#    openfeign:
#      httpclient:
#        hc5:
#          enabled: true # default : false. If false, use sun.net.www.http.HttpClient
feign:
  name: user
  url: https://retoolapi.dev/qisjDm/data
logging:
  level:
    root: info