springdoc:
  swagger-ui: # for swagger ui
    path: /swagger-ui.html
  api-docs: # for Open API yaml
    path: /v3/api-docs
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true